USE Contenedores
GO 
CREATE PROCEDURE BODEGAS 
@NOMBRE VARCHAR(50),
@LATITUD FLOAT,
@LONGITUD FLOAT
AS
BEGIN 
INSERT INTO Contenedor (Nombre,Latitud,Longitud) 
VALUES (@NOMBRE, @LATITUD, @LONGITUD)
END